language: node_js
# 指定node_js版本
node_js: 
  - lts/*
cache:	# 缓存，提高下次构建的效率
 
  directories:
    - node_modules

install:    # 安装阶段（详细的各阶段顺序，请查询 Travis-CI 相关文档）
  - npm install

script:    # 执行构建阶段
  #- hexo clean    # hexo 的清理命令
 # - hexo generate    # hexo 的生成（构建）命令，即最核心的生成静态文件过程
after_script:
  - cd ./public
  - git init
  - git config user.name "JoshuaZZZs" # --{GitHub账户名称}
  - git config user.email "15979089154@189.cn" #--{Github账户邮箱}
  - git add .
  - git commit -m "Update From Travis-cli"
   # Github Pages
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
    # Coding Pages
  - git push --force --quiet "https://zhoushaung:${CO_TOKEN}@${CO_REF}" master:master

# E: Build LifeCycle

branches:
  only:
    - hexo #--{Hexo源码分支名称}
env:
 global:
   - GH_REF:  github.com/JoshuaZZZs/JoshuaZZZs.github.io.git # --{仓库地址}
   - CO_REF:  git@e.coding.net:zhoushaung/zhoushaungPage.git